
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package clases;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int menor_igual_que = 23;
  public static final int Operacion = 38;
  public static final int Metodo = 40;
  public static final int sensorProximidad = 35;
  public static final int suma = 3;
  public static final int resta = 4;
  public static final int mayor_que = 22;
  public static final int Clase = 44;
  public static final int igual = 17;
  public static final int parentesis_cerrado = 10;
  public static final int reservada = 39;
  public static final int igual_que = 20;
  public static final int multiplicacion = 5;
  public static final int comienzo = 2;
  public static final int encenderWALLY = 24;
  public static final int apagarWALLY = 25;
  public static final int si = 14;
  public static final int rotarIzquierda = 28;
  public static final int mientras = 16;
  public static final int menor_que = 21;
  public static final int base = 36;
  public static final int rotarDerecha = 29;
  public static final int Cadena = 42;
  public static final int rueda = 34;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int parentesis_abierto = 9;
  public static final int delimitador_derecho = 8;
  public static final int point = 12;
  public static final int tareaRobot = 37;
  public static final int avanzarRobot = 32;
  public static final int Presentacion = 45; 
  public static final int wait = 33;
  public static final int delimIzq = 7;
  public static final int bajarBase = 31;
  public static final int avanzar = 26;
  public static final int Identificador = 43;
  public static final int mayor_igual_que = 19;
  public static final int fin_linea = 13;
  public static final int reversa = 27;
  public static final int diferente_que = 18;
  public static final int separador = 11;
  public static final int Numero = 41;
  public static final int division = 6;
  public static final int sino = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "comienzo",
  "suma",
  "resta",
  "multiplicacion",
  "division",
  "delimitador_izquierdo",
  "delimitador_derecho",
  "parentesis_abierto",
  "parentesis_cerrado",
  "separador",
  "punto",
  "fin_linea",
  "si",
  "sino",
  "mientras",
  "igual",
  "diferente_que",
  "mayor_igual_que",
  "igual_que",
  "menor_que",
  "mayor_que",
  "menor_igual_que",
  "encenderWALLY",
  "apagarWALLY",
  "avanzar",
  "reversa",
  "rotarIzquierda",
  "rotarDerecha",
  "subirBase",
  "bajarBase",
  "avanzarRueda",
  "espera",
  "rueda",
  "sensorProximidad",
  "base",
  "funcion",
  "Operacion",
  "reservada",
  "Metodo",
  "Numero",
  "Cadena",
  "Identificador",
  "Clase",
  "presentacion"
  };
}

